# Generated by Django 5.2.2 on 2025-06-07 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kultur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flaeche_ha', models.DecimalField(decimal_places=2, max_digits=7)),
                ('parzellenname', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pflanzenschutzmittel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zulassungsnr', models.CharField(max_length=50, unique=True)),
                ('produktname', models.CharField(max_length=255)),
                ('wirkstoff', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Behandlung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('anwendungszeitpunkt', models.CharField(max_length=100)),
                ('eigene_notizen', models.TextField(blank=True)),
                ('kultur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behandlungen', to='plaene.kultur')),
            ],
        ),
        migrations.CreateModel(
            name='Landwirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('betriebsname', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=50)),
                ('berater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Entwurf', 'Entwurf'), ('Finalisiert', 'Finalisiert')], default='Entwurf', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('zuletzt_bearbeitet', models.DateTimeField(auto_now=True)),
                ('landwirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaene', to='plaene.landwirt')),
            ],
        ),
        migrations.AddField(
            model_name='kultur',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kulturen', to='plaene.plan'),
        ),
        migrations.CreateModel(
            name='ProduktInBehandlung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufwandmenge', models.DecimalField(decimal_places=3, max_digits=7)),
                ('einheit', models.CharField(default='l/ha', max_length=10)),
                ('behandlung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkte_im_mix', to='plaene.behandlung')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plaene.pflanzenschutzmittel')),
            ],
        ),
    ]
