# Generated by Django 5.2.2 on 2025-06-07 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaene', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KulturMetadaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blv_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SchaderregerMetadaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blv_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zulassung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufwandmenge', models.CharField(max_length=100)),
                ('anzahl_anwendungen', models.CharField(max_length=100)),
                ('wartefrist', models.CharField(max_length=255)),
                ('kultur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaene.kulturmetadaten')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaene.pflanzenschutzmittel')),
                ('schaderreger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaene.schaderregermetadaten')),
            ],
            options={
                'unique_together': {('produkt', 'kultur', 'schaderreger')},
            },
        ),
        migrations.AddField(
            model_name='pflanzenschutzmittel',
            name='zugelassene_anwendungen',
            field=models.ManyToManyField(related_name='produkte', through='plaene.Zulassung', to='plaene.kulturmetadaten'),
        ),
    ]
