# Generated by Django 5.2.2 on 2025-06-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaene', '0002_kulturmetadaten_schaderregermetadaten_zulassung_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuflageMetadaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blv_id', models.CharField(max_length=50, unique=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='zulassung',
            name='aufwandmenge_einheit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='zulassung',
            name='dosage_from',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='zulassung',
            name='dosage_to',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='zulassung',
            name='anzahl_anwendungen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zulassung',
            name='aufwandmenge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zulassung',
            name='wartefrist',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='zulassung',
            name='auflagen',
            field=models.ManyToManyField(blank=True, to='plaene.auflagemetadaten'),
        ),
    ]
